# Setup
title:        react-frame-table
tagline:      React table for huge data sets
baseurl:      "/react-frame-table"
github_url:   "https://github.com/insolite/react-frame-table"

# About/contact
author:
  name:       Oleg Krasnikov
  url:        https://github.com/insolite

# Gems

#Others
markdown: kramdown