name: 'NPM Repository package publish'
on:
  push:
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# Allow one concurrent deployment
concurrency:
  group: "npm"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: npm
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --no-progress --non-interactive
      - name: Build and Publish
        run: yarn package:publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
