name: 'GitHub Pages Storybook Publish'

on:
  push:
    branches:
      - master
jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: c-hive/gha-yarn-cache@v2
      - name: Dependencies
        run: yarn
      - name: Build
        run: yarn storybook:build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: examples/storybook/storybook-static
