name: 'GitHub Pages Storybook Publish'

on:
  push:
    branches:
      - master
jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Dependencies
        run: yarn
        uses: ./
      - name: Build
        run: yarn storybook:build
        uses: ./
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: examples/storybook/storybook-static
